name: Rust

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: cargo build --release --verbose
    - name: Verify Binary Exists
      run: |
        if (!(Test-Path "./target/release/malibu-bouncer.exe")) {
          Write-Host "Error: Binary not found at ./target/release/malibu-bouncer.exe"
          exit 1
        }
        $size = (Get-Item "./target/release/malibu-bouncer.exe").Length
        Write-Host "Binary size: $size bytes"
    - name: Create Release and Upload Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "Automated release for ${{ github.ref_name }}" \
          ./target/release/malibu-bouncer.exe#malibu-bouncer-${{ github.ref_name }}-windows-x86_64.exe || \
        gh release upload ${{ github.ref_name }} \
          ./target/release/malibu-bouncer.exe#malibu-bouncer-${{ github.ref_name }}-windows-x86_64.exe
